apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: donation-portal
          image: 654654204927.dkr.ecr.eu-north-1.amazonaws.com/donation_app:latest
          ports:
            - containerPort: 5000
