apiVersion: v1
kind: Service
metadata:
  name: webapp-extservice
  namespace: default
spec:
  selector:
      app: webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000

